### ISSUE TITLE
作者您好，当存在听说实训类无上课时间地点的课程时，该插件无法导出ics文件，建议添加以下代码

### ISSUE THREAD

**Issue by lashila** [KiWeng/uestc-graduate-shedule#1]
![image](https://user-images.githubusercontent.com/87009025/221424318-6dc165f2-f2d9-48cd-be05-e61ae6182941.png)

**Comment by zh-weng** [comment]
[fixed](https://github.com/KiWeng/uestc-graduate-shedule/commit/a8be1340b4b8620ea77c2496b8b9f483a41c8c88)
